### PR TITLE
Add ScalarLeafs validation

### LINKED ISSUE #19: VariablesDefaultValueAllowed rule no longer exists
👋😄

I'm working on adding support for `graphql-cats` to [`rmosolgo/graphql-ruby`](https://github.com/rmosolgo/graphql-ruby) and in the process I noticed that the `VariablesDefaultValueAllowed` rule no longer exists as of https://github.com/graphql/graphql-js/pull/1274.

I'm assuming that at some point we may want to remove [`scenarios/validation/VariablesDefaultValueAllowed.yaml`](https://github.com/graphql-cats/graphql-cats/blob/f5561165d556ce3c24abd356192fd3273fa55352/scenarios/validation/VariablesDefaultValueAllowed.yaml) as it specifically tests the `VariablesDefaultValueAllowed` validation rule.

Just opening this issue so we don't forget.

### PR DESCRIPTION
**Pull request by cjoudrey**
Fixes #19 

This PR removes the `VariablesDefaultValueAllowed` scenario as this rule [no longer exists in GraphQL.js](https://github.com/graphql/graphql-js/pull/1274).

This PR also adds a new `ScalarLeafs` scenario which I've automatically generated [from the tests in GraphQL.js](https://github.com/graphql/graphql-js/blob/4f92f55a74477fde3b00eb99f9a37f1ff2d1bd0d/src/validation/__tests__/ScalarLeafs-test.js). If you are happy with the output, it wouldn't be too hard for me to open more PRs with additional scenarios.

I was hoping these would pass in Sangria, but they currently fail because the error messages are slightly different.

For example:

- GraphQL.js: Field "doesKnowCommand" must not have a selection since type "Boolean" has no subfields.
- Sangria: Field 'doesKnowCommand' of type 'Boolean' must not have a sub selection.

cc @OlegIlyenko

### CODE REVIEW

**Comment by OlegIlyenko** [comment]
It looks great, thanks a lot!

> I was hoping these would pass in Sangria, but they currently fail because the error messages are slightly different.

It's ok for the moment being. During the last WG meeting we discussed this aspect (error assertions is one of the top challenges):

https://github.com/graphql/graphql-wg/blob/master/notes/2018-05-24.md#there-is-currently-no-standard-error-messages-in-the-spec-the-implementations-can-reliably-use

As a next step, we decided to try adding a new concept for the error assertions - a small mapping that maps human error text to an error code with a set of parameters. We hope that it will help to define implementation-independent assertions and still allow implementations to have their own text for human error messages (by adjusting this mapping if necessary).

> If you are happy with the output, it wouldn't be too hard for me to open more PRs with additional scenarios.

This sounds great! I would appreciate it if you do so. But before doing it, I would suggest to implement the change I have described above. I think it should be pretty minor change, just one level of indirection for error messages.  I would like to prepare a PR for it (I will try to do it this weekend), and I think then we can continue with other validations.

**Comment by cjoudrey** [comment]
> a small mapping that maps human error text to an error code with a set of parameters

That's a great idea and will make CATS pass on `graphql-ruby` easier too. 🎉 

Is this what you had in mind?

```yaml
  - name: object type missing selection
    given:
      query: |
        query directQueryOnObjectWithoutSubFields {
          human
        }
    when:
      validate:
        - ScalarLeafs
    then:
      - error-count: 1
      - error: RequiredSubselection
        args: {fieldName: "human", type: "Human"}
        loc: {line: 2, column: 3}
```

Just to clarify, the mapping between `RequiredSubselection` and the error message (`'Field "$fieldName" of type "$type" must have a selection of subfields. Did you mean "human { ... }"?'`) would live in each implementation and not in `graphql-cats/graphql-cats`, correct? We don't want implementations to have to update `graphql-cats` every time they change an error message, right?

**Comment by OlegIlyenko** [comment]
Yeah, you got it right. I wanted to implement something very similar to what you have described. 

We can also store all of the default message texts in a separate yaml file (e.g. `error-mapping.yaml`), the one that you see in the reference implementation (I also wanted to add some meta info for every error message, e.g. link to a place in the spec and reference implementation, to make it clear which part of the spec covers it). I think this file can be added in `graphql-cats`. But implementations can then override all or some of them as they see fit. These overrides can live outside of the `graphql-cats`. WDYT?

**Comment by cjoudrey** [comment]
Sounds great! :+1:

I'll open a PR that modifies `ScalarLeafs` with these ideas and we can discuss exact details there. 😄 

This is really exciting!

**Pull request merged**
